apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    image.opencontainers.org/created: "2020-02-06T13:55:48-05:00"
    stack.appsody.dev/authors: Erin Schnabel <schnabel@us.ibm.com>, Ozzy Osborne <ozzy@ca.ibm.com>
    stack.appsody.dev/configured: docker.io/appsody/java-spring-boot2:0.3
    stack.appsody.dev/created: "2020-02-06T09:17:56Z"
    stack.appsody.dev/description: Spring Boot using OpenJ9 and Maven
    stack.appsody.dev/licenses: Apache-2.0
    stack.appsody.dev/tag: docker.io/appsody/java-spring-boot2:0.3.23
    stack.appsody.dev/title: Spring Boot®
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: sample-java-spring-boot2
    stack.appsody.dev/id: java-spring-boot2
    stack.appsody.dev/version: 0.3.23
  name: sample-java-spring-boot2
spec:
  applicationImage: dev.local/sample-java-spring-boot2
  createKnativeService: true
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    endpoints:
    - path: /actuator/prometheus
    labels:
      k8s-app: sample-java-spring-boot2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
status: {}
