apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    architecture: x86_64
    authoritative-source-url: registry.access.redhat.com
    build-date: 2019-10-29T16:44:53.794580
    commit.image.appsody.dev/author: Daniel Cleyrat <dacleyra@us.ibm.com>
    commit.image.appsody.dev/committer: Daniel Cleyrat <dacleyra@us.ibm.com>
    commit.image.appsody.dev/date: Thu Nov 14 10:42:23 2019 -0500
    commit.image.appsody.dev/message: license
    description: This image contains the Kabanero development stack for the java-spring-boot2
      collection
    distribution-scope: public
    image.opencontainers.org/created: "2019-11-19T09:05:06-05:00"
    image.opencontainers.org/revision: 9aba216c1a8f362ae6833986595e0911d7b742fa-modified
    k8s.io/description: The Universal Base Image is designed and engineered to be
      the base layer for all of your containerized applications, middleware and utilities.
      This base image is freely redistributable, but Red Hat only supports Red Hat
      technologies through subscriptions for Red Hat products. This image is maintained
      by Red Hat and updated regularly.
    k8s.io/display-name: Red Hat Universal Base Image 8
    maintainer: Red Hat, Inc.
    name: kabanero/java-spring-boot2
    openshift.io/expose-services: ""
    openshift.io/tags: base rhel8
    redhat.com/build-host: cpt-1002.osbs.prod.upshift.rdu2.redhat.com
    redhat.com/component: ubi8-container
    redhat.com/license_terms: https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI
    release: "277"
    stack.appsody.dev/configured: kabanero/java-spring-boot2:0.3
    stack.appsody.dev/created: 2019-11-18T19:08:21+0000
    stack.appsody.dev/revision: 82c11bd3fda141fc56df6653a58a3567dfe87d46
    stack.appsody.dev/tag: kabanero/java-spring-boot2:0.3.16
    summary: Image for Kabanero java-spring-boot2 development
    url: https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.1-277
    vcs-ref: c42933bcdbf9f1c232e981a5e40de257c3534c8e
    vcs-type: git
    vendor: Kabanero
    version: 0.2.10
  labels:
    image.opencontainers.org/title: sample-java-spring-boot2
    stack.appsody.dev/version: 0.3.16
  name: sample-java-spring-boot2
spec:
  applicationImage: dev.local/sample-java-spring-boot2
  createKnativeService: true
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/liveness
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  readinessProbe:
    failureThreshold: 12
    httpGet:
      path: /actuator/health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/path: /actuator/prometheus
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: java-spring-boot2
  version: 1.0.0
